version: "3.1"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./app
      dockerfile: dockerfile
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
