#compose.yaml
version : "3.1"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3308:3306"
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
  wordpress:
    image: wordpress
    restart: always
    ports: 
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root 
      WORDPRESS_DB_NAME: wp_database
      #password: BbDkNHvgIBaFp#^lIt
    volumes: 
      - wordpress:/var/www/html
volumes:
  db:
  wordpress: